// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-f-GttRKbvnQnrfykwOJ2APrg5i-Jjcc',
    appId: '1:681528699135:web:8069878f575dd429f984ca',
    messagingSenderId: '681528699135',
    projectId: 'chatapp-6e2b5',
    authDomain: 'chatapp-6e2b5.firebaseapp.com',
    databaseURL: 'https://chatapp-6e2b5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-6e2b5.appspot.com',
    measurementId: 'G-243GJF11XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPAmQfj1vXNdFh2TKjPjXhnH5Sr6sbGuU',
    appId: '1:681528699135:android:b1df5a656f13c67af984ca',
    messagingSenderId: '681528699135',
    projectId: 'chatapp-6e2b5',
    databaseURL: 'https://chatapp-6e2b5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-6e2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7czQhkxJRivL8Iiw0VjQaxAEM2I5xWY',
    appId: '1:681528699135:ios:89507d40601d0a89f984ca',
    messagingSenderId: '681528699135',
    projectId: 'chatapp-6e2b5',
    databaseURL: 'https://chatapp-6e2b5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-6e2b5.appspot.com',
    iosClientId: '681528699135-1naa6oe1pf60hv95ft6l4g42job59l0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx7czQhkxJRivL8Iiw0VjQaxAEM2I5xWY',
    appId: '1:681528699135:ios:89507d40601d0a89f984ca',
    messagingSenderId: '681528699135',
    projectId: 'chatapp-6e2b5',
    databaseURL: 'https://chatapp-6e2b5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-6e2b5.appspot.com',
    iosClientId: '681528699135-1naa6oe1pf60hv95ft6l4g42job59l0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
